version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    entrypoint: ["./start_app.sh"]
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: tg_bot_db
    restart: always
    environment:
      POSTGRES_USER: tg_bot_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tg_bot_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    network_mode: bridge

volumes:
  pgdata: