services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    entrypoint: ["./start_app.sh"]
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: tg_bot_db
    hostname: tg_bot_db
    restart: always
    environment:
      POSTGRES_USER: tg_bot_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tg_bot_db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: